import { Module } from '@nestjs/common';
import { AdminController } from './admin.controller';
import { AdminService } from './admin.service';
import {
  AdminOrganizationService,
  AdminUserService,
  AdminEventService,
  AdminPaymentService,
  AdminPayoutService,
  AdminRefundService,
  AdminCategoryService,
  AdminAuditService,
  AdminSettingsService,
  AdminVenueCatalogService,
  AdminVenuesService,
  AdminDisputeService,
  AdminFeeScheduleService,
  AdminTaxRateService,
  AdminSessionService,
  AdminWebhookService,
  AdminRevenueService,
  AdminModerationService,
  AdminNotificationService,
  AdminReviewService,
  AdminOrderService,
  AdminTicketService,
  AdminPromotionService,
} from './services';
import {
  AdminSessionController,
  AdminWebhookController,
  AdminRevenueController,
  AdminModerationController,
  AdminNotificationController,
  AdminReviewController,
  AdminOrderController,
  AdminTicketController,
  AdminPromotionController,
  AdminUserController,
  AdminOrganizationController,
  AdminVenueController,
  AdminFeeScheduleController,
  AdminTaxRateController,
  AdminRefundController,
  AdminDisputeController,
} from './controllers';
import { CommonModule } from '../common/common.module';
import { OrdersModule } from '../orders/orders.module';
import { QueuesModule } from '../queues/queues.module';

@Module({
  imports: [CommonModule, QueuesModule, OrdersModule],
  controllers: [
    AdminController,
    AdminSessionController,
    AdminWebhookController,
    AdminUserController,
    AdminOrganizationController,
    AdminVenueController,
    AdminFeeScheduleController,
    AdminTaxRateController,
    AdminRefundController,
    AdminDisputeController,
    AdminRevenueController,
    AdminModerationController,
    AdminNotificationController,
    AdminReviewController,
    AdminOrderController,
    AdminTicketController,
    AdminPromotionController,
  ],
  providers: [
    AdminService,
    AdminOrganizationService,
    AdminUserService,
    AdminEventService,
    AdminPaymentService,
    AdminPayoutService,
    AdminRefundService,
    AdminCategoryService,
    AdminAuditService,
    AdminSettingsService,
    AdminVenueCatalogService,
    AdminVenuesService,
    AdminDisputeService,
    AdminFeeScheduleService,
    AdminTaxRateService,
    AdminSessionService,
    AdminWebhookService,
    AdminRevenueService,
    AdminModerationService,
    AdminNotificationService,
    AdminReviewService,
    AdminOrderService,
    AdminTicketService,
    AdminPromotionService,
  ],
})
export class AdminModule {}
